# coding: utf-8

"""
    L3S Gateway for SEARCH

    Welcome to the Swagger UI documentation site!  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from l3s_gateway_client_v110.api_client import ApiClient


class RecsysServiceApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_get_n_random_recommendation(self, **kwargs):  # noqa: E501
        """get_get_n_random_recommendation  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_get_n_random_recommendation(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int num_of_recs:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_get_n_random_recommendation_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_get_n_random_recommendation_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_get_n_random_recommendation_with_http_info(self, **kwargs):  # noqa: E501
        """get_get_n_random_recommendation  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_get_n_random_recommendation_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int num_of_recs:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['num_of_recs']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_get_n_random_recommendation" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'num_of_recs' in params:
            query_params.append(('num_of_recs', params['num_of_recs']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/l3s-recsys/random-recs/get-n-paths', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_get_n_random_skills(self, **kwargs):  # noqa: E501
        """get_get_n_random_skills  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_get_n_random_skills(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int num_of_recs:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_get_n_random_skills_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_get_n_random_skills_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_get_n_random_skills_with_http_info(self, **kwargs):  # noqa: E501
        """get_get_n_random_skills  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_get_n_random_skills_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int num_of_recs:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['num_of_recs']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_get_n_random_skills" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'num_of_recs' in params:
            query_params.append(('num_of_recs', params['num_of_recs']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/l3s-recsys/random-recs/get-n-skills', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_get_n_random_tasks(self, **kwargs):  # noqa: E501
        """get_get_n_random_tasks  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_get_n_random_tasks(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int num_of_recs:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_get_n_random_tasks_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_get_n_random_tasks_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_get_n_random_tasks_with_http_info(self, **kwargs):  # noqa: E501
        """get_get_n_random_tasks  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_get_n_random_tasks_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int num_of_recs:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['num_of_recs']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_get_n_random_tasks" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'num_of_recs' in params:
            query_params.append(('num_of_recs', params['num_of_recs']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/l3s-recsys/random-recs/get-n-tasks', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_recommendation_service(self, **kwargs):  # noqa: E501
        """get_recommendation_service  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_recommendation_service(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: DtoRecsysConnectionResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_recommendation_service_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_recommendation_service_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_recommendation_service_with_http_info(self, **kwargs):  # noqa: E501
        """get_recommendation_service  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_recommendation_service_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: DtoRecsysConnectionResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_recommendation_service" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/l3s-recsys/connection', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='DtoRecsysConnectionResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_trends_search_jobs(self, loc, job_name, **kwargs):  # noqa: E501
        """get_trends_search_jobs  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_trends_search_jobs(loc, job_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str loc: (required)
        :param str job_name: (required)
        :param int radius:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_trends_search_jobs_with_http_info(loc, job_name, **kwargs)  # noqa: E501
        else:
            (data) = self.get_trends_search_jobs_with_http_info(loc, job_name, **kwargs)  # noqa: E501
            return data

    def get_trends_search_jobs_with_http_info(self, loc, job_name, **kwargs):  # noqa: E501
        """get_trends_search_jobs  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_trends_search_jobs_with_http_info(loc, job_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str loc: (required)
        :param str job_name: (required)
        :param int radius:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['loc', 'job_name', 'radius']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_trends_search_jobs" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'loc' is set
        if ('loc' not in params or
                params['loc'] is None):
            raise ValueError("Missing the required parameter `loc` when calling `get_trends_search_jobs`")  # noqa: E501
        # verify the required parameter 'job_name' is set
        if ('job_name' not in params or
                params['job_name'] is None):
            raise ValueError("Missing the required parameter `job_name` when calling `get_trends_search_jobs`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'loc' in params:
            query_params.append(('loc', params['loc']))  # noqa: E501
        if 'job_name' in params:
            query_params.append(('job_name', params['job_name']))  # noqa: E501
        if 'radius' in params:
            query_params.append(('radius', params['radius']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/l3s-recsys/trends/search-jobs', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
